# Base configs
baseurl: "https://natureandwild.life"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Nature And Wildlife Photography"
subtitle: "by Chrstina Emond"
author: "Christina Emond"
header:
 title: "Nature And Wildlife Photography"
 subtitle: ""
footer:
 name: ""
 bio: ""
 github: ""
web_design: ""
social_urls:
  facebook: "#"
  twitter: "#"
  instagram: "#"
  dribbble: "#"
  linkedin: "#"
  github: "#"
